"""Audit logging service — failures must not crash the main request."""

from typing import Optional

from sqlalchemy.orm import Session

from app.core.logging import get_logger
from app.models.audit_log import AuditLog

logger = get_logger(__name__)

# IAM audit actions
USER_CREATED = "USER_CREATED"
USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
USER_LOGIN_FAILED = "USER_LOGIN_FAILED"
USER_PROFILE_VIEWED = "USER_PROFILE_VIEWED"
USER_DISABLED = "USER_DISABLED"
USER_ENABLED = "USER_ENABLED"
TOKEN_VALIDATED = "TOKEN_VALIDATED"

# Railway organization and device management (Phase S4)
RAILWAY_ZONE_CREATED = "RAILWAY_ZONE_CREATED"
RAILWAY_ZONE_UPDATED = "RAILWAY_ZONE_UPDATED"
RAILWAY_ZONE_ACTIVATED = "RAILWAY_ZONE_ACTIVATED"
RAILWAY_ZONE_DEACTIVATED = "RAILWAY_ZONE_DEACTIVATED"
RAILWAY_DIVISION_CREATED = "RAILWAY_DIVISION_CREATED"
RAILWAY_DIVISION_UPDATED = "RAILWAY_DIVISION_UPDATED"
RAILWAY_DIVISION_ACTIVATED = "RAILWAY_DIVISION_ACTIVATED"
RAILWAY_DIVISION_DEACTIVATED = "RAILWAY_DIVISION_DEACTIVATED"
RAILWAY_STATION_CREATED = "RAILWAY_STATION_CREATED"
RAILWAY_STATION_UPDATED = "RAILWAY_STATION_UPDATED"
RAILWAY_STATION_ACTIVATED = "RAILWAY_STATION_ACTIVATED"
RAILWAY_STATION_DEACTIVATED = "RAILWAY_STATION_DEACTIVATED"
RAILWAY_CROSSING_CREATED = "RAILWAY_CROSSING_CREATED"
RAILWAY_CROSSING_UPDATED = "RAILWAY_CROSSING_UPDATED"
RAILWAY_CROSSING_ACTIVATED = "RAILWAY_CROSSING_ACTIVATED"
RAILWAY_CROSSING_DEACTIVATED = "RAILWAY_CROSSING_DEACTIVATED"
RAILWAY_CROSSING_STATUS_CHANGED = "RAILWAY_CROSSING_STATUS_CHANGED"
DEVICE_REGISTERED = "DEVICE_REGISTERED"
DEVICE_UPDATED = "DEVICE_UPDATED"
DEVICE_ASSIGNED = "DEVICE_ASSIGNED"
DEVICE_UNASSIGNED = "DEVICE_UNASSIGNED"
DEVICE_STATUS_CHANGED = "DEVICE_STATUS_CHANGED"
DEVICE_HEALTH_STATUS_CHANGED = "DEVICE_HEALTH_STATUS_CHANGED"
DEVICE_ACTIVATED = "DEVICE_ACTIVATED"
DEVICE_DEACTIVATED = "DEVICE_DEACTIVATED"
SENSOR_REGISTERED = "SENSOR_REGISTERED"
SENSOR_UPDATED = "SENSOR_UPDATED"
SENSOR_STATUS_CHANGED = "SENSOR_STATUS_CHANGED"
SENSOR_HEALTH_STATUS_CHANGED = "SENSOR_HEALTH_STATUS_CHANGED"
SENSOR_ACTIVATED = "SENSOR_ACTIVATED"
SENSOR_DEACTIVATED = "SENSOR_DEACTIVATED"
STAFF_ASSIGNMENT_CREATED = "STAFF_ASSIGNMENT_CREATED"
STAFF_ASSIGNMENT_UPDATED = "STAFF_ASSIGNMENT_UPDATED"
STAFF_ASSIGNMENT_ACTIVATED = "STAFF_ASSIGNMENT_ACTIVATED"
STAFF_ASSIGNMENT_DEACTIVATED = "STAFF_ASSIGNMENT_DEACTIVATED"


def create_audit_log(
    db: Session,
    *,
    actor: str,
    action: str,
    entity_type: str,
    entity_id: Optional[str] = None,
    details: Optional[str] = None,
) -> Optional[AuditLog]:
    """Persist an audit log record. Returns None if logging fails."""
    try:
        record = AuditLog(
            actor=actor,
            action=action,
            entity_type=entity_type,
            entity_id=entity_id,
            details=details,
        )
        db.add(record)
        db.commit()
        db.refresh(record)
        return record
    except Exception:
        db.rollback()
        logger.exception("Failed to write audit log: action=%s actor=%s", action, actor)
        return None
