"""Role permission groups for railway organization APIs (baseline Phase S4)."""

from app.models.user import (
    ROLE_CROSSING_OPERATOR,
    ROLE_DIVISION_ADMIN,
    ROLE_MAINTENANCE_ENGINEER,
    ROLE_RAILWAY_ADMIN,
    ROLE_SAFETY_INSPECTOR,
    ROLE_STATION_MASTER,
    ROLE_SUPER_ADMIN,
    ROLE_VIEWER,
)

# Full organization hierarchy management
ZONE_WRITE_ROLES = [ROLE_SUPER_ADMIN, ROLE_RAILWAY_ADMIN]
DIVISION_WRITE_ROLES = [ROLE_SUPER_ADMIN, ROLE_RAILWAY_ADMIN]
STATION_WRITE_ROLES = [ROLE_SUPER_ADMIN, ROLE_RAILWAY_ADMIN, ROLE_DIVISION_ADMIN]
CROSSING_WRITE_ROLES = [
    ROLE_SUPER_ADMIN,
    ROLE_RAILWAY_ADMIN,
    ROLE_DIVISION_ADMIN,
]
CROSSING_STATUS_WRITE_ROLES = [
    ROLE_SUPER_ADMIN,
    ROLE_RAILWAY_ADMIN,
    ROLE_DIVISION_ADMIN,
    ROLE_STATION_MASTER,
]
DEVICE_WRITE_ROLES = [
    ROLE_SUPER_ADMIN,
    ROLE_RAILWAY_ADMIN,
    ROLE_DIVISION_ADMIN,
]
DEVICE_MAINTENANCE_ROLES = [
    ROLE_SUPER_ADMIN,
    ROLE_RAILWAY_ADMIN,
    ROLE_DIVISION_ADMIN,
    ROLE_MAINTENANCE_ENGINEER,
]
SENSOR_WRITE_ROLES = DEVICE_WRITE_ROLES
SENSOR_MAINTENANCE_ROLES = DEVICE_MAINTENANCE_ROLES
STAFF_ASSIGNMENT_WRITE_ROLES = [
    ROLE_SUPER_ADMIN,
    ROLE_RAILWAY_ADMIN,
    ROLE_DIVISION_ADMIN,
]

# Read access — baseline: authenticated railway roles
ORG_READ_ROLES = [
    ROLE_SUPER_ADMIN,
    ROLE_RAILWAY_ADMIN,
    ROLE_DIVISION_ADMIN,
    ROLE_STATION_MASTER,
    ROLE_CROSSING_OPERATOR,
    ROLE_MAINTENANCE_ENGINEER,
    ROLE_SAFETY_INSPECTOR,
    ROLE_VIEWER,
]
